apiVersion: v1
kind: Service
metadata:
  name: messages-service
  labels:
    app: messages-service
spec:
  type: ClusterIP
  selector:
    app: messages-service
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
