apiVersion: v1
kind: Service
metadata:
  name: drawings-service
  labels:
    app: drawings-service
spec:
  type: ClusterIP
  selector:
    app: drawings-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
