apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawings-service
  namespace: whiteboard
  labels:
    app: drawings-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawings-service
  template:
    metadata:
      labels:
        app: drawings-service
    spec:
      containers:
        - name: drawings-service
          image: drawings-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
