apiVersion: v1
kind: Service
metadata:
  name: rooms-service
  namespace: whiteboard
  labels:
    app: rooms-service
spec:
  type: ClusterIP
  selector:
    app: rooms-service
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
