apiVersion: v1
kind: Service
metadata:
  name: drawings-service
  namespace: {{ .Values.namespace }}
  labels:
    app: drawings-service
spec:
  type: ClusterIP
  selector:
    app: drawings-service
  ports:
    - port: {{ .Values.drawings.port }}
      targetPort: {{ .Values.drawings.port }}
      protocol: TCP
      name: http
