apiVersion: v1
kind: Service
metadata:
  name: rooms-service
  namespace: {{ .Values.namespace }}
  labels:
    app: rooms-service
spec:
  type: ClusterIP
  selector:
    app: rooms-service
  ports:
    - port: {{ .Values.rooms.port }}
      targetPort: {{ .Values.rooms.port }}
      protocol: TCP
      name: http
